import bcryptjs from "bcryptjs";
import User from "../models/User.js";
import CacheService from "./cache.service.js";
import {
  ValidationError,
  AuthenticationError,
  ConflictError,
  NotFoundError,
  DatabaseError,
} from "../lib/errors.js";
import {
  validateEmail,
  validatePassword,
  validateFullName,
  validateBio,
  validateUserId,
} from "./validation.service.js";

/**
 * ============================================
 * USER SERVICE
 * ============================================
 * 
 * Handles user-related operations:
 * - Registration & login
 * - Profile updates
 * - Presence management
 * - User discovery
 */

export class UserService {
  /**
   * ============================================
   * AUTHENTICATION
   * ============================================
   */

  /**
   * Register new user
   * 
   * Steps:
   * 1. Validate inputs
   * 2. Check email uniqueness
   * 3. Hash password (bcryptjs with 12 rounds)
   * 4. Create user in database
   * 5. Return user (without password)
   */
  static async signup(signupData) {
    // 1. VALIDATE
    const email = validateEmail(signupData.email);
    const password = validatePassword(signupData.password);
    const fullName = validateFullName(signupData.fullName);

    // 2. CHECK UNIQUENESS
    try {
      const existingUser = await User.findOne({ email });
      if (existingUser) {
        throw new ConflictError(
          `User with email ${email} already exists. Try logging in instead.`
        );
      }
    } catch (err) {
      if (err.isOperational) throw err;
      console.error("Database error checking email:", err);
      throw new DatabaseError("Failed to register user");
    }

    // 3. HASH PASSWORD
    // bcryptjs.hash is async (runs in worker thread)
    // 12 rounds = ~250ms per hash = good security vs UX tradeoff
    let hashedPassword;
    try {
      hashedPassword = await bcryptjs.hash(password, 12);
    } catch (err) {
      console.error("Password hashing failed:", err);
      throw new DatabaseError("Failed to register user");
    }

    // 4. CREATE USER
    try {
      const newUser = new User({
        email,
        password: hashedPassword,
        fullName,
        status: "offline",
        lastSeen: new Date(),
      });

      await newUser.save();

      // Return without password
      return this._formatUser(newUser);
    } catch (err) {
      console.error("Failed to create user:", err);
      throw new DatabaseError("Failed to register user");
    }
  }

  /**
   * Login user
   * 
   * Steps:
   * 1. Find user by email
   * 2. Verify password
   * 3. Return user (JWT generated by auth controller)
   */
  static async login(email, password) {
    // 1. VALIDATE
    email = validateEmail(email);

    // 2. FIND USER
    try {
      const user = await User.findOne({ email });
      if (!user) {
        throw new AuthenticationError("Invalid email or password");
      }

      // 3. VERIFY PASSWORD
      const isPasswordCorrect = await bcryptjs.compare(password, user.password);
      if (!isPasswordCorrect) {
        throw new AuthenticationError("Invalid email or password");
      }

      return this._formatUser(user);
    } catch (err) {
      if (err.isOperational) throw err;
      console.error("Login failed:", err);
      throw new DatabaseError("Login failed");
    }
  }

  /**
   * ============================================
   * PROFILE MANAGEMENT
   * ============================================
   */

  /**
   * Update user profile
   * Can update: fullName, bio, profilePic
   */
  static async updateProfile(userId, updateData) {
    userId = validateUserId(userId);

    // Validate what we're updating
    const updates = {};

    if (updateData.fullName !== undefined) {
      updates.fullName = validateFullName(updateData.fullName);
    }

    if (updateData.bio !== undefined) {
      updates.bio = validateBio(updateData.bio);
    }

    if (updateData.profilePic !== undefined) {
      if (typeof updateData.profilePic !== "string") {
        throw new ValidationError("Profile picture must be a URL");
      }
      updates.profilePic = updateData.profilePic;
    }

    if (Object.keys(updates).length === 0) {
      throw new ValidationError("No valid updates provided");
    }

    try {
      const user = await User.findByIdAndUpdate(userId, updates, { new: true });

      if (!user) {
        throw new NotFoundError("User", userId);
      }

      return this._formatUser(user);
    } catch (err) {
      if (err.isOperational) throw err;
      console.error("Failed to update profile:", err);
      throw new DatabaseError("Failed to update profile");
    }
  }

  /**
   * ============================================
   * PRESENCE MANAGEMENT
   * ============================================
   */

  /**
   * Mark user as online
   * Called when user connects via WebSocket
   */
  static async setOnline(userId, socketId) {
    userId = validateUserId(userId);

    try {
      // Update database
      await User.findByIdAndUpdate(userId, {
        status: "online",
        lastSeen: new Date(),
      });

      // Update Redis cache
      await CacheService.setUserOnline(userId, socketId);
    } catch (err) {
      console.error("Failed to set user online:", err);
      // Non-critical, don't throw
    }
  }

  /**
   * Mark user as offline
   * Called when user disconnects
   */
  static async setOffline(userId) {
    userId = validateUserId(userId);

    try {
      // Update database
      await User.findByIdAndUpdate(userId, {
        status: "offline",
        lastSeen: new Date(),
      });

      // Update Redis cache
      await CacheService.setUserOffline(userId);
    } catch (err) {
      console.error("Failed to set user offline:", err);
      // Non-critical, don't throw
    }
  }

  /**
   * ============================================
   * USER DISCOVERY
   * ============================================
   */

  /**
   * Get all users except current user
   * Used for contacts/users to chat with
   */
  static async getAllUsers(userId) {
    userId = validateUserId(userId);

    try {
      const users = await User.find({
        _id: { $ne: userId },
      })
        .select("-password")
        .sort({ fullName: 1 });

      // Enrich with online status from Redis
      const enrichedUsers = await Promise.all(
        users.map(async (user) => {
          const isOnline = await CacheService.isUserOnline(user._id.toString());
          const lastSeen = await CacheService.getUserLastSeen(user._id.toString());
          return {
            ...user.toObject(),
            isOnline,
            lastSeen: lastSeen || user.lastSeen,
          };
        })
      );

      return enrichedUsers;
    } catch (err) {
      console.error("Failed to get all users:", err);
      throw new DatabaseError("Failed to fetch users");
    }
  }

  /**
   * Get user by ID
   */
  static async getUserById(userId) {
    userId = validateUserId(userId);

    try {
      const user = await User.findById(userId).select("-password");

      if (!user) {
        throw new NotFoundError("User", userId);
      }

      const isOnline = await CacheService.isUserOnline(userId);
      const lastSeen = await CacheService.getUserLastSeen(userId);

      return {
        ...user.toObject(),
        isOnline,
        lastSeen: lastSeen || user.lastSeen,
      };
    } catch (err) {
      if (err.isOperational) throw err;
      console.error("Failed to get user:", err);
      throw new DatabaseError("Failed to fetch user");
    }
  }

  /**
   * Search users by name
   */
  static async searchUsers(query, userId, limit = 20) {
    userId = validateUserId(userId);

    if (!query || typeof query !== "string") {
      throw new ValidationError("Search query is required");
    }

    const searchQuery = query.trim();
    if (searchQuery.length < 2) {
      throw new ValidationError("Search query must be at least 2 characters");
    }

    if (limit < 1 || limit > 100) {
      throw new ValidationError("Limit must be between 1 and 100");
    }

    try {
      // Case-insensitive search using regex
      const users = await User.find({
        _id: { $ne: userId },
        fullName: { $regex: searchQuery, $options: "i" },
      })
        .select("-password")
        .limit(limit)
        .sort({ fullName: 1 });

      // Enrich with online status
      const enrichedUsers = await Promise.all(
        users.map(async (user) => {
          const isOnline = await CacheService.isUserOnline(user._id.toString());
          return {
            ...user.toObject(),
            isOnline,
          };
        })
      );

      return enrichedUsers;
    } catch (err) {
      console.error("Failed to search users:", err);
      throw new DatabaseError("Failed to search users");
    }
  }

  /**
   * ============================================
   * BLOCKING
   * ============================================
   */

  /**
   * Block a user
   */
  static async blockUser(userId, blockedUserId) {
    userId = validateUserId(userId);
    blockedUserId = validateUserId(blockedUserId);

    if (userId === blockedUserId) {
      throw new ValidationError("You cannot block yourself");
    }

    try {
      const user = await User.findByIdAndUpdate(
        userId,
        { $addToSet: { blockedUsers: blockedUserId } }, // $addToSet prevents duplicates
        { new: true }
      );

      if (!user) {
        throw new NotFoundError("User", userId);
      }

      return this._formatUser(user);
    } catch (err) {
      if (err.isOperational) throw err;
      console.error("Failed to block user:", err);
      throw new DatabaseError("Failed to block user");
    }
  }

  /**
   * Unblock a user
   */
  static async unblockUser(userId, blockedUserId) {
    userId = validateUserId(userId);
    blockedUserId = validateUserId(blockedUserId);

    try {
      const user = await User.findByIdAndUpdate(
        userId,
        { $pull: { blockedUsers: blockedUserId } },
        { new: true }
      );

      if (!user) {
        throw new NotFoundError("User", userId);
      }

      return this._formatUser(user);
    } catch (err) {
      if (err.isOperational) throw err;
      console.error("Failed to unblock user:", err);
      throw new DatabaseError("Failed to unblock user");
    }
  }

  /**
   * Check if user is blocked
   */
  static async isUserBlocked(userId, potentialBlockerId) {
    userId = validateUserId(userId);
    potentialBlockerId = validateUserId(potentialBlockerId);

    try {
      const user = await User.findById(potentialBlockerId);
      if (!user) return false;

      return user.blockedUsers.some(
        (id) => id.toString() === userId.toString()
      );
    } catch (err) {
      console.error("Failed to check block status:", err);
      return false;
    }
  }

  /**
   * ============================================
   * HELPER METHODS
   * ============================================
   */

  /**
   * Format user object (remove password, convert to plain object)
   */
  static _formatUser(user) {
    const userObj = user.toObject ? user.toObject() : user;
    delete userObj.password;
    return userObj;
  }
}

export default UserService;
